workflow:
  rules:
    # - if: $CI_EXTERNAL_PULL_REQUEST_IID # disable pull requests for now
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  GIT_SUBMODULE_STRATEGY: recursive

buildLinux:
  script:
    - echo TEST_PULL_REQUEST_LINUX
    - ./linuxBuild.sh
  tags:
    - linuxX64
buildMac:
  script: echo TEST_PULL_REQUEST_MAC
  tags:
    - macos
buildWindows:
  script: echo TEST_PULL_REQUEST_WIN
  tags:
    - windowsX64

