buildLinux:
  script:
    - echo TEST_PULL_REQUEST_LINUX
    - ./linuxBuild.sh
  tags:
    - linuxX64
buildMac:
  script: echo TEST_PULL_REQUEST_MAC
  tags:
    - macos
buildWindows:
  script: echo TEST_PULL_REQUEST_WIN
  tags:
    - windowsX64

