workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
buildLinux:
  script:
    - echo TEST_PULL_REQUEST_LINUX
    - env
  tags:
    - linuxX64
buildMac:
  script: echo TEST_PULL_REQUEST_MAC
  tags:
    - macos
buildWindows:
  script: echo TEST_PULL_REQUEST_WIN
  tags:
    - windowsX64

